from __future__ import annotations

from nl2spl.compiler.construct_plan import (
    APICallArgumentBindingIR,
    APICallDemand,
    APICallPlacementIR,
    APIDeclarationDemand,
    ConstructPlan,
    OperationCoverageIR,
)
from nl2spl.ir.resource_registry_ir import APISpec, ResourceRegistryIR
from nl2spl.ir.span_ir import SpanIR
from nl2spl.ir.step_ir import StepIR
from nl2spl.ir.worker_plan_ir import WorkerStepPlanIR
from nl2spl.pipeline.stages.stage6_resource_extractor.api_materialization import (
    APICallBindingIR,
    APIMaterializationPlanIR,
)
from nl2spl.pipeline.stages.stage7_step_extractor.api_call_materializer import (
    materialize_direct_api_calls,
)


def test_characterize_s16_duplicate_operation_and_missing_residual() -> None:
    # 1. Setup fallback general command generated by LLM StepExtractor
    worker_steps = WorkerStepPlanIR(
        main_worker_id="worker_main",
        worker_steps={
            "worker_main": [
                StepIR(
                    step_id="st_fallback_s16",
                    text="Retrieve sources using approved source recipes.",
                    source_span_ids=["s16"],
                    command_type="GENERAL_COMMAND",
                    metadata={"fallback_for_api_call_demand_id": "api_call_s16"},
                )
            ]
        },
    )

    # 2. Setup APICallDemand and plan matching s16
    plan = ConstructPlan(
        plan_id="cp_internal_comms",
        api_call_argument_bindings=[
            APICallArgumentBindingIR(
                call_demand_id="api_call_s16",
                binding_status="not_required",
                source_span_ids=("s16",),
            )
        ],
        demands=[
            APIDeclarationDemand(
                demand_id="api_decl_s16",
                explicit_name_candidates=["ApprovedSourceRecipesAPI"],
                integration_admission="confirmed",
                mechanism_status="explicit",
                source_span_ids=["s15"],
            ),
            APICallDemand(
                demand_id="api_call_s16",
                declaration_demand_id="api_decl_s16",
                api_group_id="approved_source_recipes",
                action_text="retrieve them using approved source recipes",
                source_span_ids=["s16"],
                operation_coverage=[
                    OperationCoverageIR(
                        coverage_id="cov_s16_api",
                        source_span_id="s16",
                        operation_surface=(
                            "If sources are needed and available, "
                            "retrieve them using approved source recipes."
                        ),
                        char_start=0,
                        char_end=81,
                    )
                ],
                consumes_behavior_span_ids=["s16"],
                residual_behavior_span_ids=["s16"],
                behavior_lowering_policy="api_call_augments_behavior",
            ),
        ],
    )

    api_plan = APIMaterializationPlanIR(
        bindings=[
            APICallBindingIR(
                api_binding_id="api_binding:api_decl_s16",
                declaration_demand_id="api_decl_s16",
                api_id="api:ApprovedSourceRecipesAPI",
                api_name="ApprovedSourceRecipesAPI",
                call_demand_ids=["api_call_s16"],
                source_span_ids=["s15"],
            )
        ]
    )

    placement = APICallPlacementIR(
        call_demand_id="api_call_s16",
        owner_worker_id="worker_main",
        flow_ref="main",
        block_ref="block_main",
        status="placed",
        source_span_ids=["s16"],
    )

    resources = ResourceRegistryIR(
        apis=[
            APISpec(
                api_id="api:ApprovedSourceRecipesAPI",
                api_name="ApprovedSourceRecipesAPI",
                auth="none",
                description="Partial API declaration for ApprovedSourceRecipesAPI.",
                declaration_status="partial_blocked",
                schema_status="unknown_placeholder",
                functions_status="unknown_placeholder",
                functions=[],
            )
        ]
    )

    spans = [
        SpanIR(span_id="s15", text="ApprovedSourceRecipesAPI declaration."),
        SpanIR(
            span_id="s16",
            text=(
                "If sources are needed and available, retrieve them using approved "
                "source recipes. Maintain provenance for externally sourced facts."
            ),
        ),
    ]

    # 3. Execute materializer
    materialize_direct_api_calls(
        worker_steps,
        plan,
        api_plan,
        [placement],
        resources,
        spans,
    )

    steps = worker_steps.worker_steps["worker_main"]

    # NEW CORRECT BEHAVIOR ASSERTIONS:
    # 1. Fallback st_fallback_s16 is removed.
    # 2. CALL_API is materialized.
    # 3. Residual GENERAL_COMMAND "Maintain provenance for externally sourced facts." is appended.
    assert [step.command_type for step in steps] == ["CALL_API", "GENERAL_COMMAND"]
    assert steps[0].integration_ref == "ApprovedSourceRecipesAPI"
    assert steps[1].text == "Maintain provenance for externally sourced facts."
