"""Comparison report generation for Stage 1 Shadow Mode."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from nl2spl.ir.diagnostics import CompileDiagnostic
from nl2spl.pipeline.stages.stage1_segmentation.segmentation_payload import SpanSegmentationRecord
from nl2spl.pipeline.stages.stage1_segmentation.source_buffer import SectionSourceBuffer


class Stage1ShadowReporter:
    """Generates comparison reports between legacy span slicing and shadow LLM segmentation."""

    @staticmethod
    def generate_report(
        legacy_spans: Sequence[Any],
        shadow_records: Sequence[SpanSegmentationRecord],
        diagnostics: Sequence[CompileDiagnostic],
        source_buffers: dict[str, SectionSourceBuffer],
    ) -> dict[str, Any]:
        """Compute metrics comparing legacy and shadow runs.

        Args:
            legacy_spans: List of SpanIR generated by the legacy path
            shadow_records: List of SpanSegmentationRecord generated by validated shadow path
            diagnostics: List of validation diagnostics/errors
            source_buffers: Source buffers grouped by section ID

        Returns:
            Dictionary containing computed report metrics
        """
        validator_failure_count = len(diagnostics)
        fallback_count = 1 if len(shadow_records) == 0 and len(legacy_spans) > 0 else 0

        # Identify errors by checking diagnostic kinds
        coverage_gap_count = sum(1 for d in diagnostics if d.kind == "stage1_segmentation_coverage_gap")
        cross_section_merge_error_count = sum(1 for d in diagnostics if d.kind == "stage1_segmentation_cross_section_merge")

        # Check internal_comms expected guarded_action match
        # In internal_comms.txt, the expected segment is:
        # "When enough required information is available produce a draft" (or with whitespace difference)
        # Check if any shadow record is a guarded_action containing both "When enough required" and "produce a draft"
        internal_comms_guarded_action_match = False
        for rec in shadow_records:
            if rec.segmentation_kind == "guarded_action":
                text = rec.span_text.lower()
                if "when enough" in text and "produce a draft" in text:
                    internal_comms_guarded_action_match = True
                    break

        return {
            "legacy_span_count": len(legacy_spans),
            "shadow_span_count": len(shadow_records),
            "validator_failure_count": validator_failure_count,
            "fallback_count": fallback_count,
            "coverage_gap_count": coverage_gap_count,
            "cross_section_merge_error_count": cross_section_merge_error_count,
            "internal_comms_guarded_action_match": internal_comms_guarded_action_match,
        }
