from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Literal

from nl2spl.ir.diagnostics import CompileDiagnostic


class RenderMode(StrEnum):
    FULL_DOCUMENT = "full_document"
    WORKER = "worker"
    BLOCK = "block"
    STEP = "step"
    REPAIR_PREVIEW = "repair_preview"


@dataclass(frozen=True)
class RenderDiagnostic:
    """Diagnostic generated during the rendering process (display-only)."""

    diagnostic_id: str
    kind: str
    severity: Literal["error", "warning"]
    message: str
    target_ref: str
    source_span_ids: tuple[str, ...] = ()


@dataclass(frozen=True)
class RenderWarning:
    """Warning message generated by formatting or parsing in the renderer."""

    message: str
    code: str | None = None


@dataclass(frozen=True)
class RenderedDocument:
    """Presentation output generated by the Rendering Subsystem."""

    renderer_id: str
    format: Literal["spl_text", "json_tree", "html", "markdown"]
    text: str
    render_diagnostics: tuple[RenderDiagnostic, ...] = ()
    source_compile_diagnostics: tuple[CompileDiagnostic, ...] = ()


@dataclass(frozen=True)
class RenderedFragment:
    """Representation of a rendered construct fragment (e.g. step or block)."""

    format: Literal["spl_text", "json_tree", "markdown"]
    text: str
    render_diagnostics: tuple[RenderDiagnostic, ...] = ()
