"""Canonical JSON artifact snapshot -- NL2SPL <-> SPL Editing handoff contract.

This package defines the frozen compiler output document that SPL Editing
consumes.  It is owned by the compiler, not by SPL Editing internals.

Sub-packages (created in later phases):
    model/         -- SnapshotDocument, SnapshotIdentity, SnapshotPayload, etc.
    serialization/ -- Typed serializer/deserializer registry
    validation/    -- SnapshotValidator, capability deriver, integrity checker
    build/         -- SnapshotBuilder, SnapshotBuildInput, collectors
    persistence/   -- SnapshotRepository protocol, file-backed repository
"""

from __future__ import annotations

from nl2spl.compiler.artifacts.snapshot.capabilities import (
    CAPABILITIES_IN_ORDER,
    CAPABILITY_REQUIREMENT_BY_CAPABILITY,
    CAPABILITY_REQUIREMENTS,
    PRODUCTION_REQUIRED_CAPABILITIES,
    SPL_EDITING_EDITABLE_DIAGNOSTIC_KINDS,
    CapabilityRequirement,
    SnapshotCapability,
)
from nl2spl.compiler.artifacts.snapshot.constants import (
    BASE_OVERLAY_VERSION,
    IDENTITY_BASE_SNAPSHOT_ID,
    IDENTITY_COMPILE_RUN_ID,
    IDENTITY_CREATED_AT,
    IDENTITY_FIELDS,
    IDENTITY_OVERLAY_VERSION,
    IDENTITY_PARENT_SNAPSHOT_ID,
    IDENTITY_PRODUCER,
    IDENTITY_PRODUCER_VERSION,
    IDENTITY_SNAPSHOT_ID,
    INTEGRITY_ARTIFACT_SET_HASH,
    INTEGRITY_PAYLOAD_HASH,
    PAYLOAD_DIAGNOSTICS,
    PAYLOAD_EDITING,
    PAYLOAD_PROVENANCE,
    PAYLOAD_REPLAY_ARTIFACTS,
    PAYLOAD_SECTIONS,
    PAYLOAD_SOURCE,
    PAYLOAD_STAGE_ARTIFACTS,
    PRODUCER_NAME,
    SECTION_ARTIFACT_KIND,
    SECTION_CAPABILITIES,
    SECTION_IDENTITY,
    SECTION_INTEGRITY,
    SECTION_PAYLOAD,
    SECTION_SCHEMA_VERSION,
    SNAPSHOT_ARTIFACT_KIND,
    SNAPSHOT_SCHEMA_VERSION,
    TOP_LEVEL_SECTIONS,
    SnapshotMode,
    SnapshotStatus,
)
from nl2spl.compiler.artifacts.snapshot.hash_policy import (
    CANONICAL_JSON_DUMPS_KWARGS,
    CANONICAL_JSON_ENSURE_ASCII,
    CANONICAL_JSON_SEPARATORS,
    CANONICAL_JSON_SORT_KEYS,
    HASH_ALGORITHM,
    HASH_INPUT_MUST_BE_NORMALIZED,
    HASH_POLICY,
    OVERLAY_FILENAME_PREFIX,
    OVERLAY_STRATEGY,
    HashPolicy,
    canonical_json_dumps,
)
from nl2spl.compiler.artifacts.snapshot.model import (
    ArtifactRef,
    DerivedArtifactRef,
    DiagnosticsLayer,
    EditingLayer,
    ProvenanceLayer,
    ReplayArtifactsLayer,
    SnapshotAcceptedPatchDTO,
    SnapshotArtifactRefError,
    SnapshotCapabilityError,
    SnapshotCapabilityFailure,
    SnapshotDeclaredCapabilities,
    SnapshotDocument,
    SnapshotEditingHistory,
    SnapshotEffectiveCapabilities,
    SnapshotError,
    SnapshotIdentity,
    SnapshotIdentityError,
    SnapshotIntegrity,
    SnapshotIntegrityError,
    SnapshotLineageError,
    SnapshotOverlayEventDTO,
    SnapshotPayload,
    SnapshotSchemaError,
    SnapshotValidationResult,
    SnapshotVerificationRecordDTO,
    SourceLayer,
    StageArtifactsLayer,
    empty_editing_history,
    new_base_document,
    new_base_identity,
    new_overlay_document,
    new_overlay_identity,
    validate_base_identity,
    validate_overlay_lineage,
)
from nl2spl.compiler.artifacts.snapshot.schema import (
    SchemaVersionInfo,
    is_schema_compatible,
    supported_versions,
)
from nl2spl.compiler.artifacts.snapshot.serialization import (
    ArtifactSerializer,
    SerializerRegistry,
    build_default_registry,
    get_default_registry,
)

__all__ = [
    # ── constants ──
    "SNAPSHOT_ARTIFACT_KIND",
    "SNAPSHOT_SCHEMA_VERSION",
    "SECTION_ARTIFACT_KIND",
    "SECTION_SCHEMA_VERSION",
    "SECTION_IDENTITY",
    "SECTION_CAPABILITIES",
    "SECTION_PAYLOAD",
    "SECTION_INTEGRITY",
    "TOP_LEVEL_SECTIONS",
    "PAYLOAD_SOURCE",
    "PAYLOAD_STAGE_ARTIFACTS",
    "PAYLOAD_REPLAY_ARTIFACTS",
    "PAYLOAD_DIAGNOSTICS",
    "PAYLOAD_PROVENANCE",
    "PAYLOAD_EDITING",
    "PAYLOAD_SECTIONS",
    "IDENTITY_COMPILE_RUN_ID",
    "IDENTITY_SNAPSHOT_ID",
    "IDENTITY_BASE_SNAPSHOT_ID",
    "IDENTITY_PARENT_SNAPSHOT_ID",
    "IDENTITY_OVERLAY_VERSION",
    "IDENTITY_CREATED_AT",
    "IDENTITY_PRODUCER",
    "IDENTITY_PRODUCER_VERSION",
    "IDENTITY_FIELDS",
    "INTEGRITY_PAYLOAD_HASH",
    "INTEGRITY_ARTIFACT_SET_HASH",
    "PRODUCER_NAME",
    "BASE_OVERLAY_VERSION",
    "SnapshotMode",
    "SnapshotStatus",
    # ── capabilities ──
    "SnapshotCapability",
    "CAPABILITIES_IN_ORDER",
    "PRODUCTION_REQUIRED_CAPABILITIES",
    "SPL_EDITING_EDITABLE_DIAGNOSTIC_KINDS",
    "CapabilityRequirement",
    "CAPABILITY_REQUIREMENTS",
    "CAPABILITY_REQUIREMENT_BY_CAPABILITY",
    # ── schema ──
    "SchemaVersionInfo",
    "is_schema_compatible",
    "supported_versions",
    # ── hash_policy ──
    "HASH_ALGORITHM",
    "CANONICAL_JSON_SORT_KEYS",
    "CANONICAL_JSON_SEPARATORS",
    "CANONICAL_JSON_ENSURE_ASCII",
    "CANONICAL_JSON_DUMPS_KWARGS",
    "HASH_POLICY",
    "HashPolicy",
    "canonical_json_dumps",
    "OVERLAY_STRATEGY",
    "OVERLAY_FILENAME_PREFIX",
    "HASH_INPUT_MUST_BE_NORMALIZED",
    # ── model (S0) ──
    "SnapshotDocument",
    "new_base_document",
    "new_overlay_document",
    "SnapshotIdentity",
    "new_base_identity",
    "new_overlay_identity",
    "validate_base_identity",
    "validate_overlay_lineage",
    "SnapshotPayload",
    "SourceLayer",
    "StageArtifactsLayer",
    "ReplayArtifactsLayer",
    "DiagnosticsLayer",
    "ProvenanceLayer",
    "EditingLayer",
    "ArtifactRef",
    "DerivedArtifactRef",
    "SnapshotIntegrity",
    "SnapshotDeclaredCapabilities",
    "SnapshotEffectiveCapabilities",
    "SnapshotCapabilityFailure",
    "SnapshotValidationResult",
    "SnapshotEditingHistory",
    "SnapshotOverlayEventDTO",
    "SnapshotAcceptedPatchDTO",
    "SnapshotVerificationRecordDTO",
    "empty_editing_history",
    "SnapshotError",
    "SnapshotIdentityError",
    "SnapshotLineageError",
    "SnapshotCapabilityError",
    "SnapshotIntegrityError",
    "SnapshotSchemaError",
    "SnapshotArtifactRefError",
    # -- serialization (S1) --
    "ArtifactSerializer",
    "SerializerRegistry",
    "build_default_registry",
    "get_default_registry",
]
